-- AlterTable
ALTER TABLE "ComplaintVoc2" ADD COLUMN     "dateEnd" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dateStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ComplaintVoc3" ADD COLUMN     "dateEnd" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dateStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
