-- AlterTable
ALTER TABLE "PGT_title_Project" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "remaker" DROP NOT NULL,
ALTER COLUMN "transferSlip" DROP NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
